title: Pontual
description: O Pontual - Um aplicativo minimalista para apontamento

permalink: pretty

favicon: /views/static/public/icons/favicon.ico

image:
  path: /views/static/public/graph/1280x720.jpg
  width: 1280
  height: 720
  alt: Wallpaper
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
