title: O Pontual
description: O Pontual é um aplicativo que busca o minimalismo para o cliente final e oferece uma ampla gama de dados para registro de apontamento em sua empresa.

permalink: pretty

image:
  path: https://jonathanapaes.github.io/Software-Product/views/static/public/graph/512x512.jpg
  height: 512
  width: 512
  alt: O Pontual
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap