version: "3.8"
services:
  web:
    image: pontual.app:1.0
    container_name: web
    environment:
      TZ: America/Sao_Paulo    
    build: .
    working_dir: /data
    command: python app.py
    volumes:
      - .:/data
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - MyNetwork  
  db:
    image: mysql:5.7
    container_name: db
    environment: 
      MYSQL_PASSWORD: mudar123
      MYSQL_ROOT_PASSWORD: mudar123
      MYSQL_DATABASE: PONTUAL
      MYSQL_ROOT_HOST: "%"
      #MYSQL_USER: root
      TZ: America/Sao_Paulo   
    networks:
      - MyNetwork  
    ports:
      - "3306:3306" 
    #volumes:
    #  - /var/lib/mysql:/var/lib/mysql
networks:
  MyNetwork: