version: "3.8"
services:
  web:
    image: pontual.app:1.0
    container_name: web
    environment:
      TZ: America/Sao_Paulo    
    build: .
    working_dir: /data
    command: python app.py
    volumes:
      - .:/data
    ports:
      - "5000:80" # Change the port mapping to expose port 80
    networks:
      - MyNetwork
  db:
    image: mysql:5.7
    container_name: db
    environment: 
      MYSQL_PASSWORD: mudar123
      MYSQL_ROOT_PASSWORD: mudar123
      MYSQL_DATABASE: PONTUAL
      MYSQL_ROOT_HOST: "%"
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"  
    expose:
      - "3306"      
    networks:
      - MyNetwork
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" # Expose Nginx on port 80
    depends_on:
      - web
    networks:
      - MyNetwork
networks:
  MyNetwork:

